name: Semantic Release & Docker Publish

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.semantic.outputs.new_release_published }}
      version: ${{ steps.semantic.outputs.new_release_version }}
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5 # (Or whatever the absolute latest is)
        with:
          fetch-depth: 0 

      - name: Run Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v6

  build-test-push:
    name: Build and Publish Docker Image
    needs: release
    if: needs.release.outputs.published == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start application with Docker Compose
        env:
          URL: ${{ secrets.API_URL }}
          API_USER: ${{ secrets.API_USER }}
          API_PASS: ${{ secrets.API_PASS }}
          IMAGE_NAME: test-image:latest
        run: |
          docker compose up -d --build
          
      - name: Wait for app to be healthy
        run: |
          sleep 10
          while status=$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" $(docker compose ps -q web)); do
            if [ "$status" = "healthy" ]; then
              break
            elif [ "$status" = "unhealthy" ]; then
              docker compose logs web
              exit 1
            fi
            sleep 5
          done

      - name: Test the running application
        run: curl -I http://localhost:5000/

      - name: Stop Docker Compose
        run: docker compose down

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ needs.release.outputs.version }}
            type=raw,value=v${{ needs.release.outputs.version }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max